import type { Metadata } from 'next'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<script src='https://telegram.org/js/telegram-web-app.js'></script>
			</head>
			<body>{children}</body>
		</html>
	)
}
